export const galleryImages = [
    '/gallery/gallery1.jpg',
    '/gallery/gallery2.jpg',
    '/gallery/gallery3.jpg',
    '/gallery/gallery4.jpg',
    '/gallery/gallery5.jpg',
    '/gallery/gallery6.jpg',
    '/gallery/gallery7.jpg',
    '/gallery/gallery8.jpg',
    '/gallery/gallery9.jpg',
    '/gallery/gallery10.jpg',
    '/gallery/gallery11.jpg',
    '/gallery/gallery12.jpg',
    '/gallery/gallery13.jpg',
    '/gallery/gallery14.jpg',
];
