export const pastSpeakersData = [
    { name: 'Amit Jain', bio: 'CEO & CoFounder, CarDekho Group', image: '/past_speaker/Amit Jain.png' },
    { name: 'Gajendra Jangid', bio: 'CoFounder & CMO, CARS24', image: '/past_speaker/Gajendra Jangid.png' },
    { name: 'Suraj Saharan', bio: 'CoFounder, Delhivery', image: '/past_speaker/Suraj Saharan.png' },
    { name: 'Virendra Gupta', bio: 'Founder, DailyHunt', image: '/past_speaker/Virendra Gupta.png' },
    { name: 'Apurva Chamaria', bio: 'Head of Startups & Venture Capital, Google', image: '/past_speaker/Apurva Chamaria.png' },
    { name: 'Kamal Bansal', bio: 'Managing Director GVFL Ltd.', image: '/past_speaker/Kamal Bansal.png' },
    { name: 'Shankar Ram', bio: 'Chairperson, TIE Global', image: '/past_speaker/Shankar Ram.png' },
    { name: 'Satya Prakash Singh', bio: 'CEO SIDBI Venture Capital Ltd.', image: '/past_speaker/Satya Prakash Singh.png' },
    { name: 'Gurmeet Singh', bio: 'Executive Director, ESC', image: '/past_speaker/Gurmeet Singh.png' },
    { name: 'Sameep Shastri', bio: 'Vice Chairman, BRICS', image: '/past_speaker/Sameep Sharma.png' },
    { name: 'Lokendra Singh', bio: 'CoFounder & CEO, Wooden Street', image: '/past_speaker/Lokendra Singh Ranawat.png' },
    { name: 'Rameswar Misra', bio: 'CoFounder, G.O.A.T Brand Labs', image: '/past_speaker/Rameswar Misra.png' },
    { name: 'Ripunjay Bararia', bio: 'CoFounder, CTO, SugarBox', image: '/past_speaker/Ripunjay Bararia.png' },
    { name: 'Vikas Bagaria', bio: 'Founder, Pee Safe', image: '/past_speaker/Vikas Bagaria.png' },
    { name: 'Dr Ritesh Malik', bio: 'Founder & CEO, Innov8 Coworking', image: '/past_speaker/Dr. Ritesh Malik.png' },
    { name: 'Anirudh Damani', bio: 'Managing Partner, Artha Venture Fund', image: '/past_speaker/Anirudh Damani.png' },
    { name: 'Rajat Mehta', bio: 'Chairman, JITO', image: '/past_speaker/Rajat Mehta.png' },
    { name: 'Lalit Mangal', bio: 'CoFounder & CEO, Airmeet', image: '/past_speaker/Lalit Mangal.png' },
    { name: 'Nitin Sethi', bio: 'Chief Digital Officer, Adani Group', image: '/past_speaker/Nitin Sethi.png' },
    { name: 'Ashish Saboo', bio: 'President, TiE SoCal', image: '/past_speaker/Ashish Saboo.png' },
    { name: 'Khurshed Dordi', bio: 'Ex-MD & COO, Deutsche Bank (Mumbai)', image: '/past_speaker/Khurshed Dordi.png' },
    { name: 'Neeraj Sinha', bio: 'Partner BDO (Mumbai)', image: '/past_speaker/Neeraj Sinha.png' },
    { name: 'Pooja Mehta', bio: 'CIO JITO Angel Network', image: '/past_speaker/Pooja Mehta.png' },
    { name: 'Gauri Kuchhal', bio: 'Principal, Artha Venture Fund', image: '/past_speaker/Gauri Kuchhal.png' },
    { name: 'Priti Rathi Gupta', bio: 'Founder, LXME', image: '/past_speaker/Priti Rathi Gupta.png' },
]
